# Generated by Django 4.2.2 on 2024-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='time_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='time_out',
            field=models.DateTimeField(),
        ),
    ]
