# Generated by Django 4.2.2 on 2024-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_attendence_time_in_alter_attendence_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Time Off', 'Time Off')], max_length=10),
        ),
    ]
