# Generated by Django 4.2.2 on 2024-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roll',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
